{% set name = "qcportal" %}
{% set version = "0.11.0" %}
{% set sha256 = "7271f15e86c94b38c4223434f2c03f98585caa0d9108810000941e1bd7797479" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - msgpack-python>=0.6.1
    - numpy >=1.7
    - pandas
    - requests
    - pyyaml >=5.1
    - pydantic >=0.32
    - qcelemental >=0.9
    - plotly
    - py3dmol

test:
  requires:
    - pytest
  imports:
    - qcportal
  commands:
    - pytest --pyargs qcportal

about:
  home: https://github.com/MolSSI/QCPortal
  dev_url: https://github.com/MolSSI/QCPortal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/portal-client.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A client interface to the QC Archive Project

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
