{% set name = "qcportal" %}
{% set version = "0.8.1" %}
{% set sha256 = "65c66da47ca959cdc7d84e151cf4390208ad2e80e0496bae083dd5c48b78594f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy >=1.7
    - pandas
    - requests
    - pyyaml >=5.1
    - pydantic >=0.30.1
    - qcelemental >=0.5.0
    - plotly
    - py3dmol

test:
  requires:
    - pytest
  imports:
    - qcportal
  commands:
    - pytest --pyargs qcportal

about:
  home: https://github.com/MolSSI/QCPortal
  dev_url: https://github.com/MolSSI/QCPortal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/portal-client.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A client interface to the QC Archive Project

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
