{% set name = "qcportal" %}
{% set version = "0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/q/qcportal/qcportal-{{ version }}.tar.gz
    sha256: 3ef280e9225831d8021bc33c77158bb633b34bfb82691b25f12a9289f75a4429
    folder: qcportal

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps -vv ./qcportal

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - versioningit
  run:
    - python >=3.8
    - numpy
    - msgpack-python
    - requests
    - pyyaml
    - pydantic <2.0
    - zstandard
    - qcelemental
    - tabulate
    - tqdm
    - pandas
    - pyjwt

test:
  imports:
    - qcportal
  requires:
    - pip
    - pytest
  commands:
    - test -f $SP_DIR/qcportal/__init__.py
    - pip check
    - python -c "import qcportal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://molssi.github.io/QCFractal/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/main/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/license/bsd-3-clause/
  license_file: LICENSE
  license_family: BSD
  summary: Python library for interacting with QCArchive/QCFractal servers

extra:
  feedstock-name: qcportal
  recipe-maintainers:
    - lnaden
    - bennybp
