travis:
  secure:
    BINSTAR_TOKEN: FxCvwMvGO+48lpM/yg8FJjrk9bS93mu77z+MpAQe7/ZGuNK7rGg3MTA1WqZRvfx693wnVcWU/lSsHwQFSqkg8clm9mYOXwJ91nlz5sxUaIWQiHn3ahIk4+UqcwYSnFFg8qSp7svYsduLKciEJgdmVADNqwwqMvWM5xvDxZhs3AB5YXSnfNLu0+AWD0NIbwkA6L/FtoPeTwx3/8GV+oAJ7CBYFoV7MODXFez2zPA00WtGrMNaY2sK5wtSibwr8uVG97fQGPHo7KrPrZkpUY6FkiK/Zl9KfAFIYx/Pk8T1UTknVtu+iSYjnraX3z4Ujj5BrmfPfZ/1Sllk0r40FW6reZxMZO8QG/Zv293erZxXpnUkoUXyk6m4W1mlpl/J2NLwKIK51Fhah4OtnFwEciJ6E9xOIN6iR/XWery8/W3XFnPpJowiq0/aD+GdzQW14j4/I3nAbvJStSNRJN/pXq1otrlUxDvuyd7R7+qPNG/4zVbNJ6FgPHanjKZ5O0x/pqO8JovZzSj1dFAUxssNoiI8hIfbJWYaM/dapPHWp9SEeM/aKYBt/3OT2cklSqYnUVoN7sv6u+Fa442Pz42v+luzJFB8B5pxcXaZ5mtAERh9sjR3xyf1US3oVk6ugAB7N2/wa7mzj0/75RnEMXmPO4DKVLvB/sgiaasPyn1KeNvj/eQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
